---
development:
  cloud_name: delqcamot
  api_key: '555413816999314'
  api_secret: Uh9uLYSE8zX1PcjDzZILgILAZI0
  enhance_image_tag: true
  static_file_support: false
test:
  cloud_name: delqcamot
  api_key: '555413816999314'
  api_secret: Uh9uLYSE8zX1PcjDzZILgILAZI0
  enhance_image_tag: true
  static_file_support: false
